export default [
  [
    { id: "0.0", face: "JJ", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.1", face: "2S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.2", face: "3S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.3", face: "4S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.4", face: "5S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.5", face: "6S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.6", face: "7S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.7", face: "8S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.8", face: "9S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "0.9", face: "JJ", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "1.0", face: "6C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.1", face: "5C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.2", face: "4C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.3", face: "3C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.4", face: "2C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.5", face: "AH", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.6", face: "KH", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.7", face: "QH", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.8", face: "TH", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "1.9", face: "TS", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "2.0", face: "7C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.1", face: "AS", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.2", face: "2D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.3", face: "3D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.4", face: "4D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.5", face: "5D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.6", face: "6D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.7", face: "7D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.8", face: "9H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "2.9", face: "QS", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "3.0", face: "8C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.1", face: "KS", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.2", face: "6C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.3", face: "5C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.4", face: "4C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.5", face: "3C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.6", face: "2C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.7", face: "8D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.8", face: "8H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "3.9", face: "KS", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "4.0", face: "9C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.1", face: "QS", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.2", face: "7C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.3", face: "6H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.4", face: "5H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.5", face: "4H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.6", face: "AH", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.7", face: "9D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.8", face: "7H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "4.9", face: "AS", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "5.0", face: "TC", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.1", face: "TS", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.2", face: "8C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.3", face: "7H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.4", face: "2H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.5", face: "3H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.6", face: "KH", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.7", face: "TD", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.8", face: "6H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "5.9", face: "2D", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "6.0", face: "QC", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.1", face: "9S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.2", face: "9C", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.3", face: "8H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.4", face: "9H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.5", face: "TH", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.6", face: "QH", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.7", face: "QD", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.8", face: "5H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "6.9", face: "3D", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "7.0", face: "KC", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.1", face: "8S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.2", face: "TC", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.3", face: "QC", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.4", face: "KC", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.5", face: "AC", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.6", face: "AD", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.7", face: "KD", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.8", face: "4H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "7.9", face: "4D", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "8.0", face: "AC", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.1", face: "7S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.2", face: "6S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.3", face: "5S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.4", face: "4S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.5", face: "3S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.6", face: "2S", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.7", face: "2H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.8", face: "3H", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "8.9", face: "5D", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
  [
    { id: "9.0", face: "JJ", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.1", face: "AD", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.2", face: "KD", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.3", face: "QD", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.4", face: "TD", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.5", face: "9D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.6", face: "8D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.7", face: "7D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.8", face: "6D", teamId: "", partOfSequence: 0, sequenceIds: [] },
    { id: "9.9", face: "JJ", teamId: "", partOfSequence: 0, sequenceIds: [] },
  ],
] as const;

// const board = [
//   [
//     { id: "0.0", face: "JJ", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.1", face: "2S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.2", face: "3S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.3", face: "4S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.4", face: "5S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.5", face: "6S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.6", face: "7S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.7", face: "8S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.8", face: "9S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "0.9", face: "JJ", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "1.0", face: "6C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.1", face: "5C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.2", face: "4C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.3", face: "3C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.4", face: "2C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.5", face: "AH", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.6", face: "KH", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.7", face: "QH", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.8", face: "TH", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "1.9", face: "TS", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "2.0", face: "7C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.1", face: "AS", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.2", face: "2D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.3", face: "3D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.4", face: "4D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.5", face: "5D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.6", face: "6D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.7", face: "7D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.8", face: "9H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "2.9", face: "QS", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "3.0", face: "8C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.1", face: "KS", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.2", face: "6C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.3", face: "5C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.4", face: "4C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.5", face: "3C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.6", face: "2C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.7", face: "8D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.8", face: "8H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "3.9", face: "KS", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "4.0", face: "9C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.1", face: "QS", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.2", face: "7C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.3", face: "6H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.4", face: "5H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.5", face: "4H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.6", face: "AH", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.7", face: "9D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.8", face: "7H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "4.9", face: "AS", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "5.0", face: "TC", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.1", face: "TS", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.2", face: "8C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.3", face: "7H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.4", face: "2H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.5", face: "3H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.6", face: "KH", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.7", face: "TD", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.8", face: "6H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "5.9", face: "2D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "6.0", face: "QC", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.1", face: "9S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.2", face: "9C", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.3", face: "8H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.4", face: "9H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.5", face: "TH", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.6", face: "QH", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.7", face: "QD", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.8", face: "5H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "6.9", face: "3D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "7.0", face: "KC", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.1", face: "8S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.2", face: "TC", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.3", face: "QC", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.4", face: "KC", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.5", face: "AC", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.6", face: "AD", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.7", face: "KD", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.8", face: "4H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "7.9", face: "4D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "8.0", face: "AC", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.1", face: "7S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.2", face: "6S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.3", face: "5S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.4", face: "4S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.5", face: "3S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.6", face: "2S", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.7", face: "2H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.8", face: "3H", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "8.9", face: "5D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
//   [
//     { id: "9.0", face: "JJ", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.1", face: "AD", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.2", face: "KD", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.3", face: "QD", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.4", face: "TD", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.5", face: "9D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.6", face: "8D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.7", face: "7D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.8", face: "6D", teamId: "", partOfSequence: 0, sequenceIds: [] },
//     { id: "9.9", face: "JJ", teamId: "", partOfSequence: 0, sequenceIds: [] },
//   ],
// ] as const;

// const boardCopy = JSON.parse(JSON.stringify(board));

// ["3.8", "5.8", "4.8", "7.8", "6.8"]
// const caseAlreadyT = [
//   "2.5",
//   "3.5",
//   "4.5",
//   "5.5",
//   "6.5",
//   "4.5",
//   "4.6",
//   "4.7",
//   "4.8",
//   "4.9",
// ];
// caseAlreadyT.forEach((cellId) => {
//   const [x, y] = cellId.split(".").map((str) => parseInt(str, 10));
//   boardCopy[x][y] = {
//     id: cellId,
//     face: boardCopy[x][y].face,
//     teamId: "A",
//     partOfSequence: 2,
//   };
// });

// ["4.3", "4.4", "4.5", "4.6", "4.7"]
// const caseT = ["2.5", "3.5", "4.5", "5.5", "6.5"];
// caseT.forEach((cellId) => {
//   const [x, y] = cellId.split(".").map((str) => parseInt(str, 10));
//   boardCopy[x][y] = {
//     id: cellId,
//     face: boardCopy[x][y].face,
//     teamId: "A",
//     partOfSequence: 1,
//   };
// });

// ["4.4", "4.5", "4.6", "4.7", "4.8"]
// const caseParallel = [
//   "2.5",
//   "3.5",
//   "4.5",
//   "5.5",
//   "6.5",
//   "3.8",
//   "4.8",
//   "5.8",
//   "7.8",
//   "6.8",
// ];
// caseParallel.forEach((cellId) => {
//   const [x, y] = cellId.split(".").map((str) => parseInt(str, 10));
//   boardCopy[x][y] = {
//     id: cellId,
//     face: boardCopy[x][y].face,
//     teamId: "A",
//     partOfSequence: 1,
//   };
// });

// export default boardCopy;
