export default [
  [
    { id: "0.0", face: "JJ", teamId: "" },
    { id: "0.1", face: "TS", teamId: "" },
    { id: "0.2", face: "QS", teamId: "" },
    { id: "0.3", face: "KS", teamId: "" },
    { id: "0.4", face: "AS", teamId: "" },
    { id: "0.5", face: "2D", teamId: "" },
    { id: "0.6", face: "3D", teamId: "" },
    { id: "0.7", face: "4D", teamId: "" },
    { id: "0.8", face: "5D", teamId: "" },
    { id: "0.9", face: "JJ", teamId: "" },
  ],
  [
    { id: "1.0", face: "9S", teamId: "" },
    { id: "1.1", face: "TH", teamId: "" },
    { id: "1.2", face: "9H", teamId: "" },
    { id: "1.3", face: "8H", teamId: "" },
    { id: "1.4", face: "7H", teamId: "" },
    { id: "1.5", face: "6H", teamId: "" },
    { id: "1.6", face: "5H", teamId: "" },
    { id: "1.7", face: "4H", teamId: "" },
    { id: "1.8", face: "3H", teamId: "" },
    { id: "1.9", face: "6D", teamId: "" },
  ],
  [
    { id: "2.0", face: "8S", teamId: "" },
    { id: "2.1", face: "QH", teamId: "" },
    { id: "2.2", face: "7D", teamId: "" },
    { id: "2.3", face: "8D", teamId: "" },
    { id: "2.4", face: "9D", teamId: "" },
    { id: "2.5", face: "TD", teamId: "" },
    { id: "2.6", face: "QD", teamId: "" },
    { id: "2.7", face: "KD", teamId: "" },
    { id: "2.8", face: "2H", teamId: "" },
    { id: "2.9", face: "7D", teamId: "" },
  ],
  [
    { id: "3.0", face: "7S", teamId: "" },
    { id: "3.1", face: "KH", teamId: "" },
    { id: "3.2", face: "6D", teamId: "" },
    { id: "3.3", face: "2C", teamId: "" },
    { id: "3.4", face: "AH", teamId: "" },
    { id: "3.5", face: "KH", teamId: "" },
    { id: "3.6", face: "QH", teamId: "" },
    { id: "3.7", face: "AD", teamId: "" },
    { id: "3.8", face: "2S", teamId: "" },
    { id: "3.9", face: "8D", teamId: "" },
  ],
  [
    { id: "4.0", face: "6S", teamId: "" },
    { id: "4.1", face: "AH", teamId: "" },
    { id: "4.2", face: "5D", teamId: "" },
    { id: "4.3", face: "3C", teamId: "" },
    { id: "4.4", face: "4H", teamId: "" },
    { id: "4.5", face: "3H", teamId: "" },
    { id: "4.6", face: "TH", teamId: "" },
    { id: "4.7", face: "AC", teamId: "" },
    { id: "4.8", face: "3S", teamId: "" },
    { id: "4.9", face: "9D", teamId: "" },
  ],
  [
    { id: "5.0", face: "5S", teamId: "" },
    { id: "5.1", face: "2C", teamId: "" },
    { id: "5.2", face: "4D", teamId: "" },
    { id: "5.3", face: "4C", teamId: "" },
    { id: "5.4", face: "5H", teamId: "" },
    { id: "5.5", face: "2H", teamId: "" },
    { id: "5.6", face: "9H", teamId: "" },
    { id: "5.7", face: "KC", teamId: "" },
    { id: "5.8", face: "4S", teamId: "" },
    { id: "5.9", face: "TD", teamId: "" },
  ],
  [
    { id: "6.0", face: "4S", teamId: "" },
    { id: "6.1", face: "3C", teamId: "" },
    { id: "6.2", face: "3D", teamId: "" },
    { id: "6.3", face: "5C", teamId: "" },
    { id: "6.4", face: "6H", teamId: "" },
    { id: "6.5", face: "7H", teamId: "" },
    { id: "6.6", face: "8H", teamId: "" },
    { id: "6.7", face: "QC", teamId: "" },
    { id: "6.8", face: "5S", teamId: "" },
    { id: "6.9", face: "QD", teamId: "" },
  ],
  [
    { id: "7.0", face: "3S", teamId: "" },
    { id: "7.1", face: "4C", teamId: "" },
    { id: "7.2", face: "2D", teamId: "" },
    { id: "7.3", face: "6C", teamId: "" },
    { id: "7.4", face: "7C", teamId: "" },
    { id: "7.5", face: "8C", teamId: "" },
    { id: "7.6", face: "9C", teamId: "" },
    { id: "7.7", face: "TC", teamId: "" },
    { id: "7.8", face: "6S", teamId: "" },
    { id: "7.9", face: "KD", teamId: "" },
  ],
  [
    { id: "8.0", face: "2S", teamId: "" },
    { id: "8.1", face: "5C", teamId: "" },
    { id: "8.2", face: "AS", teamId: "" },
    { id: "8.3", face: "KS", teamId: "" },
    { id: "8.4", face: "QS", teamId: "" },
    { id: "8.5", face: "TS", teamId: "" },
    { id: "8.6", face: "9S", teamId: "" },
    { id: "8.7", face: "8S", teamId: "" },
    { id: "8.8", face: "7S", teamId: "" },
    { id: "8.9", face: "AD", teamId: "" },
  ],
  [
    { id: "9.0", face: "JJ", teamId: "" },
    { id: "9.1", face: "6C", teamId: "" },
    { id: "9.2", face: "7C", teamId: "" },
    { id: "9.3", face: "8C", teamId: "" },
    { id: "9.4", face: "9C", teamId: "" },
    { id: "9.5", face: "TC", teamId: "" },
    { id: "9.6", face: "QC", teamId: "" },
    { id: "9.7", face: "KC", teamId: "" },
    { id: "9.8", face: "AC", teamId: "" },
    { id: "9.9", face: "JJ", teamId: "" },
  ],
] as const;
